/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nms.tm.ui;

/**
 *
 * @author Cuong
 */
public class ThreadMonitor extends javax.swing.JFrame {

    /**
     * Creates new form ThreadMonitor
     */
    public ThreadMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        addConnBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        treeScrollPane = new javax.swing.JScrollPane();
        serverTree = new javax.swing.JTree();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NMS Thread Monitor");
        setIconImage((new javax.swing.ImageIcon(getClass().getClassLoader().getResource("com/nms/tm/image/monitor.png"))).getImage());

        toolBar.setFloatable(false);

        addConnBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("com/nms/tm/image/sign-add.png")));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/nms/tm/bundle/Bundle"); // NOI18N
        addConnBtn.setToolTipText(bundle.getString("toolbar.addConnBtn.tooltip")); // NOI18N
        addConnBtn.setFocusable(false);
        addConnBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addConnBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(addConnBtn);

        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("com/nms/tm/image/sign-info.png")));
        aboutBtn.setFocusable(false);
        aboutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aboutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(aboutBtn);

        splitPane.setDividerLocation(200);
        splitPane.setToolTipText("");

        treeScrollPane.setViewportView(serverTree);

        splitPane.setLeftComponent(treeScrollPane);
        splitPane.setRightComponent(tabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton addConnBtn;
    private javax.swing.JTree serverTree;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
}
